using AutoMapper;
using HMS.DAL.Models.PatientModule;
using HMS.BLL.Shared.Dtos.PatientModule.AllergyDtos;

namespace HMS.BLL.Services.MappingProfiles.PatientModule
{
    public class AllergyProfile : Profile
    {
        public AllergyProfile()
        {
            // PatientAllergy -> AllergyResultDto
            CreateMap<PatientAllergy, AllergyResultDto>()
                .ForMember(dest => dest.Type, options => options.MapFrom(src => src.Type.ToString()))
                .ForMember(dest => dest.Severity, options => options.MapFrom(src => src.Severity.ToString()));

            // CreateAllergyDto -> PatientAllergy
            CreateMap<CreateAllergyDto, PatientAllergy>()
                // IGNORE: Id (auto-generated by database)
                .ForMember(dest => dest.Id, options => options.Ignore())
                // IGNORE: PatientId (set in service)
                .ForMember(dest => dest.PatientId, options => options.Ignore())
                // IGNORE: RecordDate (set in service)
                .ForMember(dest => dest.RecordDate, options => options.Ignore())
                // IGNORE: Navigation Property
                .ForMember(dest => dest.Patient, options => options.Ignore());
        }
    }
}
