using AutoMapper;
using HMS.DAL.Models.PatientModule;
using HMS.BLL.Shared.Dtos.PatientModule.EmergencyContactsDtos;

namespace HMS.BLL.Services.MappingProfiles.PatientModule
{
    public class EmergencyContactProfile : Profile
    {
        public EmergencyContactProfile()
        {
            // EmergencyContact -> EmergencyContactResultDto
            CreateMap<EmergencyContact, EmergencyContactResultDto>();

            // CreateEmergencyContactDto -> EmergencyContact
            CreateMap<CreateEmergencyContactDto, EmergencyContact>()
                // IGNORE: Id (auto-generated by database)
                .ForMember(dest => dest.Id, options => options.Ignore())
                // IGNORE: PatientId (set in service)
                .ForMember(dest => dest.PatientId, options => options.Ignore())
                // IGNORE: CreatedAt (set in service)
                .ForMember(dest => dest.CreatedAt, options => options.Ignore())
                // IGNORE: UpdatedAt (null on creation)
                .ForMember(dest => dest.UpdatedAt, options => options.Ignore())
                // IGNORE: Navigation Property
                .ForMember(dest => dest.Patient, options => options.Ignore());
        }
    }
}
