using AutoMapper;
using HMS.DAL.Models.PatientModule;
using HMS.BLL.Shared.Dtos.PatientModule.Medical_History_Dtos;

namespace HMS.BLL.Services.MappingProfiles.PatientModule
{
    public class MedicalHistoryProfile : Profile
    {
        public MedicalHistoryProfile()
        {
            // PatientMedicalHistory -> MedicalHistoryResultDto
            CreateMap<PatientMedicalHistory, MedicalHistoryResultDto>()
                .ForMember(dest => dest.ConditionType, options => options.MapFrom(src => src.ConditionType.ToString()));

            // CreateMedicalHistoryDto -> PatientMedicalHistory
            CreateMap<CreateMedicalHistoryDto, PatientMedicalHistory>()
                // IGNORE: Id (auto-generated by database)
                .ForMember(dest => dest.Id, options => options.Ignore())
                // IGNORE: PatientId (set in service)
                .ForMember(dest => dest.PatientId, options => options.Ignore())
                // IGNORE: RecordedDate (set in service)
                .ForMember(dest => dest.RecordedDate, options => options.Ignore())
                // IGNORE: IsActive (set in service)
                .ForMember(dest => dest.IsActive, options => options.Ignore())
                // IGNORE: ResolutionDate (not set during creation)
                .ForMember(dest => dest.ResolutionDate, options => options.Ignore())
                // IGNORE: Navigation Property
                .ForMember(dest => dest.Patient, options => options.Ignore());
        }
    }
}
