using AutoMapper;
using HMS.DAL.Models.PatientModule;
using HMS.BLL.Shared.Dtos.PatientModule.PatientDtos;

namespace HMS.BLL.Services.MappingProfiles.PatientModule
{
    public class PatientProfile : Profile
    {
        public PatientProfile()
        {
            // Address Mapping
            CreateMap<Address, AddressDto>().ReverseMap();

            // Patient Mapping -> PatientResultDto
            CreateMap<Patient, PatientResultDto>()
                .ForMember(dest => dest.Gender, options => options.MapFrom(src => src.Gender.ToString()))
                .ForMember(dest => dest.BloodType, options => options.MapFrom(src => src.BloodType.HasValue ? src.BloodType.ToString() : null))
                .ForMember(dest => dest.Status, options => options.MapFrom(src => src.Status.ToString()))
                .ForMember(dest => dest.PictureUrl, opt => opt.MapFrom<PatientPictureUrlResolver<PatientResultDto>>());


            // CreatePatientDto -> Patient Mapping
            CreateMap<CreatePatientDto, Patient>()
    .ForMember(dest => dest.PictureUrl, opt => opt.MapFrom(src => src.PictureUrl))
    // IGNORE: Id (auto-generated by database)
    .ForMember(dest => dest.Id, options => options.Ignore())

    // IGNORE: MedicalRecordNumber (generated in service using GenerateMedicalRecordNumberAsync)
    .ForMember(dest => dest.MedicalRecordNumber, options => options.Ignore())

    // IGNORE: Status (set to Active by default in service)
    .ForMember(dest => dest.Status, options => options.Ignore())

    // IGNORE: RegistrationDate (set to current date in service)
    .ForMember(dest => dest.RegistrationDate, options => options.Ignore())

    // IGNORE: Navigation Properties (relationships with other tables)
    // These are NOT part of patient creation, they're managed separately
    .ForMember(dest => dest.PatientAllergies, options => options.Ignore())
    .ForMember(dest => dest.PatientMedicalHistories, options => options.Ignore())
    .ForMember(dest => dest.EmergencyContacts, options => options.Ignore());

            // UpdatePatientDto -> Patient Mapping
            // update is handled in the service 

            CreateMap<Patient, PatientWithDetailsResultDto>()
    .ForMember(dest => dest.Gender, opt => opt.MapFrom(src => src.Gender.ToString()))
    .ForMember(dest => dest.BloodType, opt => opt.MapFrom(src => src.BloodType.HasValue ? src.BloodType.ToString() : null))
    .ForMember(dest => dest.Status, opt => opt.MapFrom(src => src.Status.ToString()))
    .ForMember(dest => dest.Allergies, opt => opt.MapFrom(src => src.PatientAllergies))
    .ForMember(dest => dest.MedicalHistories, opt => opt.MapFrom(src => src.PatientMedicalHistories))
    .ForMember(dest => dest.EmergencyContacts, opt => opt.MapFrom(src => src.EmergencyContacts))
    .ForMember(dest => dest.PictureUrl, opt => opt.MapFrom<PatientPictureUrlResolver<PatientWithDetailsResultDto>>());

        }
    }
}
